version: 2.1
jobs:
  run_tests:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.18.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Run tests
          command: go test -v


workflows:
  build_test:
    jobs:
      - run_tests