name: automerge
on:
  pull_request:
    branches: [ "master" ]
  workflow_run:
    workflows: [Run Tests, Build Image]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: automerge

  automerge:
    needs: add-labels
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{secrets.ACCOUNT_TOKEN}}"
