name: Build and Push Image

on:
  push:
    branches: ["master"]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: pstefans/covidstats:${{github.sha}}

  notify_helm_repo:
    needs: push_to_registry
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: Patryk-Stefanski/CovidStatsHelmCharts
          event-type: new-image-tag
          client-payload: '{"ref": "${{ github.ref }}",
                            "sha": "${{ github.sha }}"
                            }'
