name: Test and Merge

on:
  pull_request:
    branches: ["master"]

env:
  COMMIT_SHA: ${{github.sha}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x

      - name: Build the Docker image using podman
        run: podman build --tag docker.io/pstefans/covidstats:$COMMIT_SHA .

  run_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          COVID_STATS_API_KEY: ${{ secrets.COVID_STATS_API_KEY }}
        run: go test -v ./...


  add-labels:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - name: add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ github.token }}
          labels: automerge

  automerge:
    needs: add-labels
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: "${{secrets.ACCOUNT_TOKEN}}"
