name: Run Tests

on:
  pull_request:
    branches: ["master"]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.3

      - name: Install dependencies
        run: go get ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          COVID_STATS_API_KEY: ${{ secrets.COVID_STATS_API_KEY }}
        run: go test -v ./...
